### ISSUE TITLE
Last release is too old please compile new one

### ISSUE THREAD

**Issue by masrourmouad** [DrFair/Game#2]

**Comment by DrFair** [comment]
First of all, thanks for showing your interest in the game. This project isn't really meant to be "public" per say. It's a project I work on alone in my spare time for fun and he only reason this repository is public, is so I can show it to people easily. All that being said, it's not a definite that the game will never go public. As I work on it more, I may find it at a place and time where I want to try and start to market it. As you have seen, it's been over 2 years since I have worked on a release, and since the game is filled with bugs in it's current state, I can't just make another release. I might work on a stable version this summer for a new release though. Again, thanks for the show of interest and the nice feedback :)
